mysql:
  host: 192.168.80.130:3306
  user: root
  pwd: root
  dbname: blog
web:
  port: 8080
webpage:
  icpinfo: '鄂ICP备 19011531号-1'
log:
  prefix: ''
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'
  logfilepath: '../log'
  modulename: 'test-log'