mysql:
  host: 127.0.0.1:3306
  user: root
  pwd: root
  dbname: blog
web:
  port: 9090
  metrics_port: 9091
  uploadpath : "./static/upload/"
webpage:
  icpinfo: '鄂ICP备 19011531号-1'
log:
  prefix: ''
  log-file: true
  stdout: 'INFO'
  file: 'INFO'
  logfilepath: './log'
  modulename: 'test-log'