mysql:
  host: 192.168.80.130:3306
  user: root
  pwd: root
  dbname: blog
web:
  port: 9090
  uploadpath : "./static/upload/"
webpage:
  icpinfo: '鄂ICP备 19011531号-1'
log:
  prefix: ''
  log-file: true
  stdout: 'INFO'
  file: 'INFO'
  logfilepath: './log'
  modulename: 'test-log'